// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/accounts": {
            "get": {
                "description": "Récupère la liste de tous les comptes financiers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Lister tous les comptes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Account"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Crée un compte financier avec des credentials chiffrés",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Créer un nouveau compte",
                "parameters": [
                    {
                        "description": "Données du compte",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Account"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/accounts/{id}": {
            "get": {
                "description": "Retourne les détails d'un compte financier",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Récupérer un compte par ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID du compte",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Account"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Supprime un compte et toutes ses données associées",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Supprimer un compte",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID du compte",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/accounts/{id}/fees": {
            "get": {
                "description": "Calcule les métriques de frais pour un compte spécifique",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fees"
                ],
                "summary": "Frais d'un compte",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID du compte",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date de début (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date de fin (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fees.FeesMetrics"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/accounts/{id}/performance": {
            "get": {
                "description": "Calcule les métriques de performance pour un compte spécifique",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "performance"
                ],
                "summary": "Performance d'un compte",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID du compte",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1y",
                        "description": "Période (1m, 3m, 1y, all)",
                        "name": "period",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/performance.Performance"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/accounts/{id}/sync": {
            "post": {
                "description": "Déclenche la synchronisation des transactions pour un compte (Binance, Bourse Direct)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sync"
                ],
                "summary": "Synchroniser un compte",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID du compte",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/accounts/{id}/sync/complete": {
            "post": {
                "description": "Finalise la synchronisation en fournissant le code de vérification",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sync"
                ],
                "summary": "Compléter la synchronisation Trade Republic avec le code 2FA",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID du compte",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Process ID et code 2FA",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CompleteSyncRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/accounts/{id}/sync/init": {
            "post": {
                "description": "Déclenche l'authentification 2FA pour Trade Republic",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sync"
                ],
                "summary": "Initier la synchronisation Trade Republic",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID du compte",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.InitSyncResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/accounts/{id}/transactions": {
            "get": {
                "description": "Retourne les transactions paginées et filtrées d'un compte",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Récupérer les transactions d'un compte",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID du compte",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date de début (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date de fin (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrer par ISIN",
                        "name": "asset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrer par type (buy, sell, dividend, fee)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Numéro de page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Nombre de résultats par page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Trier par champ (timestamp, amount)",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Ordre de tri (asc, desc)",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/assets": {
            "get": {
                "description": "Retourne tous les actifs avec les positions de l'utilisateur",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Lister les actifs avec positions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.AssetPosition"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/assets/symbols/resolve": {
            "post": {
                "description": "Déclenche la résolution des symboles Yahoo Finance pour tous les actifs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Résoudre tous les symboles manquants",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/assets/{isin}/history": {
            "get": {
                "description": "Récupère l'historique des prix pour un actif sur une période donnée",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Historique des prix d'un actif",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Code ISIN de l'actif",
                        "name": "isin",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date de début (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date de fin (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.AssetPrice"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/assets/{isin}/performance": {
            "get": {
                "description": "Calcule les métriques de performance pour un actif spécifique",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "performance"
                ],
                "summary": "Performance d'un actif",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Code ISIN de l'actif",
                        "name": "isin",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1y",
                        "description": "Période (1m, 3m, 1y, all)",
                        "name": "period",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/performance.AssetPerformance"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/assets/{isin}/price": {
            "get": {
                "description": "Récupère le prix actuel d'un actif par son code ISIN",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Prix actuel d'un actif",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Code ISIN de l'actif",
                        "name": "isin",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AssetPrice"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/assets/{isin}/price/refresh": {
            "post": {
                "description": "Supprime le cache et récupère l'historique complet des prix",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Rafraîchir les prix d'un actif",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Code ISIN de l'actif",
                        "name": "isin",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/assets/{isin}/price/update": {
            "post": {
                "description": "Force la mise à jour du prix actuel d'un actif",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Mettre à jour le prix d'un actif",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Code ISIN de l'actif",
                        "name": "isin",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/assets/{isin}/symbol": {
            "put": {
                "description": "Met à jour le symbole Yahoo Finance d'un actif",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Mettre à jour le symbole d'un actif",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Code ISIN de l'actif",
                        "name": "isin",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Symbole et statut de vérification",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Asset"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/fees": {
            "get": {
                "description": "Calcule les métriques de frais pour tous les comptes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fees"
                ],
                "summary": "Frais globaux",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Date de début (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date de fin (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fees.FeesMetrics"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/performance": {
            "get": {
                "description": "Calcule les métriques de performance pour tous les comptes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "performance"
                ],
                "summary": "Performance globale",
                "parameters": [
                    {
                        "type": "string",
                        "default": "1y",
                        "description": "Période (1m, 3m, 1y, all)",
                        "name": "period",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/performance.Performance"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/symbols/search": {
            "get": {
                "description": "Recherche un symbole sur Yahoo Finance",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "symbols"
                ],
                "summary": "Rechercher un symbole boursier",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Terme de recherche",
                        "name": "query",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/transactions": {
            "get": {
                "description": "Retourne les transactions paginées de tous les comptes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Récupérer toutes les transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Date de début (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date de fin (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrer par ISIN",
                        "name": "asset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrer par type (buy, sell, dividend, fee)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Numéro de page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Nombre de résultats par page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Trier par champ (timestamp, amount)",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Ordre de tri (asc, desc)",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/transactions/import": {
            "post": {
                "description": "Importe des transactions à partir d'un fichier CSV avec déduplication",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Importer des transactions depuis un CSV",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID du compte",
                        "name": "account_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Fichier CSV",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ImportSummary"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/transactions/{id}": {
            "put": {
                "description": "Met à jour une transaction existante",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Modifier une transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la transaction",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Données de la transaction",
                        "name": "transaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Transaction"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Transaction"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Retourne le statut de l'application et de la base de données",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "monitoring"
                ],
                "summary": "Vérifier l'état de santé de l'application",
                "responses": {
                    "200": {
                        "description": "Application healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Application unhealthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AssetPosition": {
            "type": "object",
            "properties": {
                "average_buy_price": {
                    "type": "number"
                },
                "currency": {
                    "type": "string"
                },
                "current_price": {
                    "type": "number"
                },
                "current_value": {
                    "type": "number"
                },
                "isin": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "purchases": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Purchase"
                    }
                },
                "quantity": {
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                },
                "symbol_verified": {
                    "type": "boolean"
                },
                "total_invested": {
                    "type": "number"
                },
                "unrealized_gain": {
                    "type": "number"
                },
                "unrealized_gain_pct": {
                    "type": "number"
                }
            }
        },
        "api.CompleteSyncRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "process_id": {
                    "type": "string"
                }
            }
        },
        "api.CreateAccountRequest": {
            "type": "object",
            "properties": {
                "credentials": {
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                }
            }
        },
        "api.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/api.ErrorDetail"
                }
            }
        },
        "api.ImportSummary": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "errors": {
                    "type": "integer"
                },
                "ignored": {
                    "type": "integer"
                },
                "imported": {
                    "type": "integer"
                }
            }
        },
        "api.InitSyncResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "process_id": {
                    "type": "string"
                },
                "requires_two_factor": {
                    "type": "boolean"
                }
            }
        },
        "api.Purchase": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "number"
                }
            }
        },
        "api.TransactionResponse": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                },
                "transactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Transaction"
                    }
                }
            }
        },
        "fees.FeeTimeSeriesPoint": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "fees": {
                    "type": "number"
                }
            }
        },
        "fees.FeesMetrics": {
            "type": "object",
            "properties": {
                "average_fees": {
                    "type": "number"
                },
                "fees_by_type": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                },
                "time_series": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/fees.FeeTimeSeriesPoint"
                    }
                },
                "total_fees": {
                    "type": "number"
                },
                "transaction_count": {
                    "type": "integer"
                }
            }
        },
        "models.Account": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_sync": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "platform": {
                    "description": "\"traderepublic\", \"binance\", \"boursedirect\"",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Asset": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "isin": {
                    "type": "string"
                },
                "last_updated": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "symbol_verified": {
                    "type": "boolean"
                },
                "type": {
                    "description": "\"stock\", \"etf\", \"crypto\"",
                    "type": "string"
                }
            }
        },
        "models.AssetPrice": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isin": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "models.Transaction": {
            "type": "object",
            "properties": {
                "account_id": {
                    "description": "New fields for database integration",
                    "type": "string"
                },
                "action_payload": {
                    "type": "string"
                },
                "action_type": {
                    "type": "string"
                },
                "actions": {
                    "description": "Details (when extract_details is true)",
                    "type": "string"
                },
                "amount": {
                    "type": "string"
                },
                "amount_currency": {
                    "type": "string"
                },
                "amount_fraction": {
                    "type": "integer"
                },
                "amount_value": {
                    "type": "number"
                },
                "avatar": {
                    "type": "string"
                },
                "cash_account_number": {
                    "type": "string"
                },
                "deleted": {
                    "type": "boolean"
                },
                "dividend_per_share": {
                    "type": "string"
                },
                "fees": {
                    "type": "string"
                },
                "hidden": {
                    "type": "boolean"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isin": {
                    "type": "string"
                },
                "metadata": {
                    "description": "JSON string for additional platform-specific data",
                    "type": "string"
                },
                "quantity": {
                    "type": "number"
                },
                "share_price": {
                    "type": "string"
                },
                "shares": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "subtitle": {
                    "type": "string"
                },
                "taxes": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "total": {
                    "type": "string"
                },
                "transaction_type": {
                    "description": "\"buy\", \"sell\", \"dividend\", \"fee\"",
                    "type": "string"
                }
            }
        },
        "performance.AssetPerformance": {
            "type": "object",
            "properties": {
                "current_price": {
                    "type": "number"
                },
                "isin": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "performance_pct": {
                    "type": "number"
                },
                "realized_gains": {
                    "type": "number"
                },
                "time_series": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/performance.PerformancePoint"
                    }
                },
                "total_fees": {
                    "type": "number"
                },
                "total_invested": {
                    "type": "number"
                },
                "total_quantity": {
                    "type": "number"
                },
                "total_value": {
                    "type": "number"
                },
                "unrealized_gains": {
                    "type": "number"
                }
            }
        },
        "performance.Performance": {
            "type": "object",
            "properties": {
                "cash_balance": {
                    "type": "number"
                },
                "performance_pct": {
                    "type": "number"
                },
                "realized_gains": {
                    "type": "number"
                },
                "time_series": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/performance.PerformancePoint"
                    }
                },
                "total_fees": {
                    "type": "number"
                },
                "total_invested": {
                    "type": "number"
                },
                "total_value": {
                    "type": "number"
                },
                "unrealized_gains": {
                    "type": "number"
                }
            }
        },
        "performance.PerformancePoint": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "invested": {
                    "description": "Amount invested in assets (cost basis)",
                    "type": "number"
                },
                "value": {
                    "description": "Current value of assets in EUR",
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Valhafin API",
	Description:      "API de gestion de portefeuille financier - synchronisation de comptes, suivi de performance et analyse des frais.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
